[package]
name = "mfcc-2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray="^0.15"
rustdct="^0.7"
#rustfft="^6.0"
#realfft = "^2.0.1"
ndrustfft = "^0.2.1"

